#!/bin/bash

# PKG_ARCHIVE_PATH & PKG_EXTRACT_PATH & PKG_INSTALL_PATH must be set
. pkg_init
if [[ -z "$PKG_ARCHIVE_PATH" || -z "$PKG_EXTRACT_PATH" || -z "$PKG_INSTALL_PATH" ]]; then
	echo "ERROR: package enviornment variables are not set"
	exit -1
fi

# install a premade package to the system
# param #1 = package archive file

archive_file_raw=$1
archive_file=
if [[ -e "$PKG_ARCHIVE_PATH/$archive_file_raw.tar.xz" ]]; then
	archive_file=$PKG_ARCHIVE_PATH/$archive_file_raw.tar.xz
elif [[ -e "$archive_file_raw" ]]; then
	archive_file=$archive_file_raw
else
	echo "ERROR: no such file"
	exit -1
fi
unset archive_file_raw

# make sure the extract folder exists
mkdir -p $PKG_EXTRACT_PATH
# clean extract folder of any any previous bad files (in case of previous failure)
if [[ "$(ls -A $PKG_EXTRACT_PATH)" ]]; then
	rm -rf $PKG_EXTRACT_PATH/*
fi
# dump the package archive into the extract folder
tar -xJpf $archive_file -C $PKG_EXTRACT_PATH
# copy the package into it's installed destinations
cp -Rpf $PKG_EXTRACT_PATH/* $PKG_INSTALL_PATH
# clean the extract folder of files created during this run
rm -rf $PKG_EXTRACT_PATH/*

exit 0
